### ISSUE TITLE
Linux版本安装

### ISSUE THREAD

**Issue by Jonham** [Kahaani/dieghv#1]
rime官网称Linux支持(IBus, Fcitx)这两种。
不过，我用Linux Mint，Fcitx版本安装示范是OpenSUSE。。想想还是先别装了。

有没有人用Linux装过rime的，在此讨个教程。Linux Mint我是新手。

**Comment by kahaani** [comment]
感谢你的关注。

我不了解Linux Mint，下面是Ubuntu上的安装方法，希望对你有帮助。

# 安装

在Ubuntu上可以运行下面的命令，其他发行版请参考[这份说明](https://github.com/rime/home/wiki/RimeWithIBus)。

```
sudo apt-get install ibus-rime
```

在语言栏设置中开启ibus-rime，就可以打字了，默认预装有「明月拼音」和「仓颉五代」。

# 添加潮语拼音

以潮州音为例，把下面三个文件放到用户文件夹`~/.config/ibus/rime/`。

```
dieziu.schema.yaml
dieziu.dict.yaml
default.custom.yaml
```

其中，`default.custom.yaml`文件的内容如下：

```
patch:
  schema_list:
    - schema: luna_pinyin    # 朙月拼音
    - schema: dieziu         # 潮語拼音〔潮州〕
```

# 布署

点击语言栏上的⟲(Deploy)按钮，或者运行下面命令：

```
rm ~/.config/ibus/rime/default.yaml; ibus-daemon -drx
```

# todo

在[「潮语拼音教程」的附录二](http://kahaani.github.io/gatian/appendix2/index.html)添加「Linux版安装说明」。
